apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: "pipeline_combustiveis"
  namespace: processing
spec:
  timeToLiveSeconds: 60
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "maylatt/spark-operator:3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: local:///app/jobs/ingestion_job.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  driver:
    volumeMounts:
      - name: ivy
        mountPath: /tmp
    secrets:
      - name: "gcp-credentials"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    cores: 1
    coreRequest: '100m'
    coreLimit: "500m"    
    memory: "2Gi"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    volumeMounts:
      - name: ivy
        mountPath: /tmp
    secrets:
      - name: "gcp-credentials"
        path: "/mnt/secrets"
        secretType: GCPServiceAccount
    cores: 1
    coreRequest: '100m'
    coreLimit: "1000m"    
    instances: 2
    memory: "2Gi"
    labels:
      version: 3.1.1
  volumes:
    - name: ivy
      emptyDir: { }
